name: UtilityCommands
main: com.github.neapovil.utilitycommands.UtilityCommands
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/utilitycommands
depend:
  - CommandAPI
